/* U0 welcome/onboarding — EN/ES copy. Maintained candidate, NOT integrated.
 *
 * Source: docs/reports/WELCOME-AND-ONBOARDING-CONTRACT-2026-09-18.md ("Compact screen sequence and
 * copy", "Solaris beyond the first step"). Strings marked (host) reuse the
 * retained host's own wording and Spanish (sanctuary.html 763/1013/1033).
 * Everything else was written for this candidate and has had NO qualified
 * EN/ES copy review. No model size, no diagnosis claim, no wallet/reward
 * activation. Keys must match exactly between locales (tests enforce it).
 */

export const LOCALES = Object.freeze(['en', 'es']);

const en = {
  'brand.word': 'SOLARIS',
  'a11y.emblem': 'Solaris emblem',
  'a11y.progress': 'Step {n} of {total}',
  'lang.button': 'Español',
  'lang.target': 'es',
  'common.retry': 'Try again',
  'common.back': 'Back',
  'common.continue': 'Continue',
  'common.skip': 'Skip for now',
  'common.close': 'Close',
  'pending.view': 'Checking…',
  'pending.setup': 'Opening vault setup…',
  'pending.aiSetup': 'Opening Pocket LUCA AI setup…',
  'pending.saving': 'Saving…',

  'opening.title': 'Opening Solaris…',
  'opening.body': 'Solaris is checking the state of your vault on this phone.',
  'opening.slow': 'This is taking longer than usual. This screen does not create or change a vault.',
  'opening.error': 'Solaris could not confirm the state of your vault. This screen does not create or change a vault. Try again.',
  'opening.invalid': 'Solaris received a vault state it cannot use. Nothing was created or changed here. Try again.',

  'welcome.title': 'Your health. Your space.',
  'welcome.body': 'A place for your records, your reflections and your next small step.',
  'welcome.start': 'Get started',
  'welcome.restore': 'I have a vault to restore',
  'welcome.setupNote': 'Both options open vault setup on this phone.',
  'welcome.aiNote': 'Pocket LUCA AI is optional. You can set it up later.',
  'welcome.vision': 'The wider Solaris vision',

  'native.title': 'Make this space yours.',
  'native.body': 'Set up or restore your vault using the available device and recovery options.',

  'returning.title': 'Welcome back.',
  'returning.body': 'Unlock your vault to continue.',
  'returning.unlock': 'Unlock my vault',
  'returning.recovery': 'Recovery help opens from the same vault screen. Your recovery passphrase is only for recovery files.',
  'returning.aiSetup': 'Pocket LUCA AI setup',

  'migration.eyebrow': 'ONE-TIME OWNER SETUP', // (host)
  'migration.title': 'Your earlier records are here.', // (host)
  'migration.body': 'Save and verify your recovery file before beginning the protected daily companion.', // (host)
  'migration.setup': 'Continue Vault setup', // (host)

  'ch1.title': 'You choose what LUCA can use.',
  'ch1.body': 'Your records are personal. Choose the records LUCA may use, within your permissions. Review the sources chosen for each personal reply.',
  'ch1.note': 'This introduction does not add or remove any source choice.',

  'ch2.title': 'Support, on your phone.',
  'ch2.body': 'Pocket LUCA offers brief local help. Personal answers need the records you choose. You can use your daily tools without AI.',
  'ch2.greetingLabel': 'Guided example · written in advance, not generated by AI',
  'ch2.greeting': 'Hello. I can offer brief help with the records you choose.',
  'ch2.setup': 'Set up Pocket LUCA',
  'ch2.withoutAI': 'Continue without AI',
  'ch2.note': 'Setup opens Pocket LUCA AI setup on this phone. This introduction does not download or start a model.',

  'ch3.title': 'One small step, at your pace.',
  'ch3.body': 'You can explore now and complete your profile later.',
  'ch3.nameLabel': 'What would you like to be called? (optional)',
  'ch3.done': 'Done',
  'ch3.doneCheckin': 'Finish and check in',
  'ch3.doneRecords': 'Finish and open my records',

  'error.setupFailed': 'Vault setup could not be opened. Try again.',
  'error.aiSetupFailed': 'Pocket LUCA AI setup could not be opened. You can continue without AI.',
  'error.doneFailed': 'Solaris could not confirm that the introduction is finished. Your name entry is kept. Try again.',
  'error.doneTimeout': 'Saving has not been confirmed yet. Your name entry is kept. Try again.',
  'error.doneNotConfirmed': 'The save did not confirm the introduction as finished. Try again.',
  'error.lockedDuringSave': 'Your vault locked before this was confirmed. Unlock to continue.',
  'error.languageNotSaved': 'The language changed on this screen but could not be saved yet.',

  'vision.title': 'The wider Solaris vision',
  'vision.planned': 'Planned',
  'vision.thisApp': 'This app',
  'vision.website': 'Separate website',
  'vision.vault.title': 'Health passport on this phone',
  'vision.vault.body': 'This Android vault keeps your records on this phone.',
  'vision.web.title': 'Solaris online',
  'vision.web.body': 'The website supports discovery and coordination. It has its own sign-in; this vault does not send your records to it.',
  'vision.clinic.title': 'Practitioner exchange',
  'vision.clinic.body': 'Future practitioner endpoints and Clinic OS are meant to support consented exchange. A directory entry does not prove trust, and withdrawing access later cannot recall a copy already shared.',
  'vision.economy.title': 'Economic passport and sovereignty experiments',
  'vision.economy.body': 'Wallets and GPS/RGB experiments are separately scoped future integrations. None is needed to use your vault.',
};

const es = {
  'brand.word': 'SOLARIS',
  'a11y.emblem': 'Emblema de Solaris',
  'a11y.progress': 'Paso {n} de {total}',
  'lang.button': 'English',
  'lang.target': 'en',
  'common.retry': 'Intentar de nuevo',
  'common.back': 'Atrás',
  'common.continue': 'Continuar',
  'common.skip': 'Omitir por ahora',
  'common.close': 'Cerrar',
  'pending.view': 'Comprobando…',
  'pending.setup': 'Abriendo la configuración de la bóveda…',
  'pending.aiSetup': 'Abriendo la configuración de Pocket LUCA AI…',
  'pending.saving': 'Guardando…',

  'opening.title': 'Abriendo Solaris…',
  'opening.body': 'Solaris está comprobando el estado de tu bóveda en este teléfono.',
  'opening.slow': 'Esto está tardando más de lo habitual. Esta pantalla no crea ni cambia ninguna bóveda.',
  'opening.error': 'Solaris no pudo confirmar el estado de tu bóveda. Esta pantalla no crea ni cambia ninguna bóveda. Inténtalo de nuevo.',
  'opening.invalid': 'Solaris recibió un estado de bóveda que no puede usar. Aquí no se creó ni cambió nada. Inténtalo de nuevo.',

  'welcome.title': 'Tu salud. Tu espacio.',
  'welcome.body': 'Un espacio para tus registros, tus reflexiones y tu próximo pequeño paso.',
  'welcome.start': 'Comenzar',
  'welcome.restore': 'Tengo una bóveda para restaurar',
  'welcome.setupNote': 'Ambas opciones abren la configuración de la bóveda en este teléfono.',
  'welcome.aiNote': 'Pocket LUCA AI es opcional. Puedes configurarlo más tarde.',
  'welcome.vision': 'La visión de Solaris',

  'native.title': 'Haz tuyo este espacio.',
  'native.body': 'Configura o restaura tu bóveda con las opciones disponibles del dispositivo y de recuperación.',

  'returning.title': 'Te damos la bienvenida de nuevo.',
  'returning.body': 'Desbloquea tu bóveda para continuar.',
  'returning.unlock': 'Desbloquear mi bóveda',
  'returning.recovery': 'La ayuda de recuperación se abre desde la misma pantalla de la bóveda. Tu frase de recuperación es solo para archivos de recuperación.',
  'returning.aiSetup': 'Configuración de Pocket LUCA AI',

  'migration.eyebrow': 'CONFIGURACIÓN INICIAL DEL PROPIETARIO',
  'migration.title': 'Tus registros anteriores están aquí.',
  'migration.body': 'Guarda y verifica tu archivo de recuperación antes de comenzar con el compañero diario protegido.',
  'migration.setup': 'Continuar configuración de la bóveda',

  'ch1.title': 'Tú eliges qué puede usar LUCA.',
  'ch1.body': 'Tus registros son personales. Elige los registros que puede usar LUCA, según tus permisos. Revisa las fuentes elegidas para cada respuesta personal.',
  'ch1.note': 'Esta introducción no añade ni quita ninguna selección de fuentes.',

  'ch2.title': 'Apoyo en tu teléfono.',
  'ch2.body': 'Pocket LUCA ofrece ayuda breve en tu teléfono. Las respuestas personales necesitan los registros que elijas. Puedes usar tus herramientas diarias sin IA.',
  'ch2.greetingLabel': 'Ejemplo guiado · escrito de antemano, no generado por IA',
  'ch2.greeting': 'Hola. Puedo ofrecer ayuda breve con los registros que elijas.',
  'ch2.setup': 'Configurar Pocket LUCA',
  'ch2.withoutAI': 'Continuar sin IA',
  'ch2.note': 'La configuración abre Pocket LUCA AI en este teléfono. Esta introducción no descarga ni inicia ningún modelo.',

  'ch3.title': 'Un paso pequeño, a tu ritmo.',
  'ch3.body': 'Puedes explorar ahora y completar tu perfil más adelante.',
  'ch3.nameLabel': '¿Cómo te gustaría que te llamemos? (opcional)',
  'ch3.done': 'Listo',
  'ch3.doneCheckin': 'Terminar y registrar mi día',
  'ch3.doneRecords': 'Terminar y abrir mis registros',

  'error.setupFailed': 'No se pudo abrir la configuración de la bóveda. Inténtalo de nuevo.',
  'error.aiSetupFailed': 'No se pudo abrir la configuración de Pocket LUCA AI. Puedes continuar sin IA.',
  'error.doneFailed': 'Solaris no pudo confirmar que la introducción terminó. Se conserva el nombre que escribiste. Inténtalo de nuevo.',
  'error.doneTimeout': 'Aún no se ha confirmado el guardado. Se conserva el nombre que escribiste. Inténtalo de nuevo.',
  'error.doneNotConfirmed': 'El guardado no confirmó que la introducción terminó. Inténtalo de nuevo.',
  'error.lockedDuringSave': 'Tu bóveda se bloqueó antes de confirmarse. Desbloquéala para continuar.',
  'error.languageNotSaved': 'El idioma cambió en esta pantalla, pero aún no se pudo guardar.',

  'vision.title': 'La visión de Solaris',
  'vision.planned': 'En desarrollo',
  'vision.thisApp': 'Esta aplicación',
  'vision.website': 'Sitio web aparte',
  'vision.vault.title': 'Pasaporte de salud en este teléfono',
  'vision.vault.body': 'Esta bóveda Android guarda tus registros en este teléfono.',
  'vision.web.title': 'Solaris en línea',
  'vision.web.body': 'El sitio web ayuda a descubrir y coordinar. Tiene su propio inicio de sesión; esta bóveda no le envía tus registros.',
  'vision.clinic.title': 'Intercambio con profesionales',
  'vision.clinic.body': 'Los futuros puntos de conexión para profesionales y Clinic OS buscan permitir un intercambio con consentimiento. Una entrada en un directorio no demuestra confianza, y retirar el acceso más tarde no puede recuperar una copia ya compartida.',
  'vision.economy.title': 'Pasaporte económico y experimentos de soberanía',
  'vision.economy.body': 'Las billeteras y los experimentos de GPS/RGB son integraciones futuras con alcance propio. Ninguna es necesaria para usar tu bóveda.',
};

export const COPY = Object.freeze({ en: Object.freeze(en), es: Object.freeze(es) });

/** Keys whose value is deliberately identical in both locales (proper nouns). */
export const SAME_IN_BOTH = Object.freeze(['brand.word']);

/** The native setup boundary copy is handed to the native screen; this candidate never renders it. */
export const NATIVE_HANDOFF_KEYS = Object.freeze(['native.title', 'native.body']);

export function normalizeLocale(value) {
  return value === 'es' ? 'es' : 'en';
}

/** Look up a string; an unknown key throws rather than rendering a raw key. */
export function t(locale, key, vars) {
  const table = COPY[normalizeLocale(locale)];
  if (!Object.hasOwn(table, key)) throw Error(`COPY_KEY_MISSING:${key}`);
  const text = table[key];
  return vars ? text.replace(/\{(\w+)\}/g, (m, k) => (Object.hasOwn(vars, k) ? String(vars[k]) : m)) : text;
}
